# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

services:
    - mysql

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install -r requirements.txt
    - mysql -e 'create database test'


before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - make check
    - make coverage
