# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "2.7"

services:
    - mysql

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install -r requirements.txt

before_script:
    - uname -a
    - printenv
    - pip list
    - mysql -e 'create database test'

script:
    - date
    - ls -al
    - make check
    - make test
