# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install flask

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - make check
