# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "2.7"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install -r requirements.txt

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - make check
    - make test
